### ISSUE TITLE
date schema is not producing ISO string

### ISSUE THREAD

**Issue by karlismelderis** [iendeavor/yup-schema-faker#155]
**Describe the bug** A clear and concise description of what the bug is.

this PR is causing us headache:
https://github.com/iendeavor/yup-schema-faker/commit/04af55743e92c173263c8173725698fd790c9ad0

as yup-schema-faker is used o create JSON object that is later sent to e.g. API 
or is used to compare back response

getting Date object doesn't let us to create working data for tests.

e.g. expect is failing here:
```ts
const expected = fake(object{
dateKey: yup.date()
})
expect(responseFromAPI).to.deep.equal(expected)
```

**Expected behavior** A clear and concise description of what you expected to happen.

I expect faker to produce ISO string (or at least expose configuration option to do so)

**Comment by iendeavor** [comment]
@karlismelderis 

We could override/extend built-in implementation:

```ts
import { date } from 'yup'
import { addFaker, DateFaker } from 'yup-schema-faker'

export class CustomDateFaker extends DateFaker {
  doFake() {
    const fakeData = super.doFake()
    return fakeData instanceof Date ? fakeData.toISOString() : fakeData
  }
}

addFaker(date, CustomDateFaker)
```

Hope this helps you 😄 .
